/**
 * @houselevi/constants/errors
 * Error codes and messages for audit logging
 */

export const ERROR_CODES = {
  AUTH_INVALID_CREDENTIALS: 'AUTH_001',
  AUTH_TOKEN_EXPIRED: 'AUTH_002',
  AUTH_TOKEN_INVALID: 'AUTH_003',
  AUTH_NOT_AUTHENTICATED: 'AUTH_004',
  AUTH_INSUFFICIENT_PERMISSIONS: 'AUTH_005',
  DEVICE_NOT_FOUND: 'DEVICE_001',
  DEVICE_LIMIT_EXCEEDED: 'DEVICE_002',
  DEVICE_NOT_TRUSTED: 'DEVICE_003',
  USER_NOT_FOUND: 'USER_001',
  USER_SUSPENDED: 'USER_002',
  PAYMENT_FAILED: 'PAYMENT_001',
  PAYMENT_DECLINED: 'PAYMENT_002',
  SUBSCRIPTION_NOT_ACTIVE: 'SUBSCRIPTION_001',
  RATE_LIMIT_EXCEEDED: 'RATE_001',
  INTERNAL_SERVER_ERROR: 'SERVER_001',
} as const;

export const ERROR_MESSAGES: Record<string, string> = {
  [ERROR_CODES.AUTH_INVALID_CREDENTIALS]: 'Invalid email or password',
  [ERROR_CODES.AUTH_TOKEN_EXPIRED]: 'Your session has expired',
  [ERROR_CODES.DEVICE_LIMIT_EXCEEDED]: 'Maximum devices reached',
  [ERROR_CODES.USER_NOT_FOUND]: 'User not found',
  [ERROR_CODES.RATE_LIMIT_EXCEEDED]: 'Too many requests',
};
