// apps/web/app/lib/travel/placeholders.ts
// Dev placeholders. heroImage.url = placeholder until admin uploads a real image.
// When admin uploads via backend, API returns the real URL  no code changes needed.
import type { TravelPackage, TravelTestimonial } from "../../lib/types/travel.types";

export const PLACEHOLDER_QUOTES = [
  { id: "1", text: "Huge thank you to Drew for the trip of a lifetime!", author: "SUSANNE E." },
  { id: "2", text: "If photography is your focus, this is an opportunity to learn from the best in the business and bring home images that will evoke the power of your experience. For those focused on other ways to capture the experience, as were 4 of the 8 in our group, this is still your trip to take.", author: "ERIN & BOB C." },
  { id: "3", text: "Traveling to East Africa with Drew was magic.", author: "ELISE L." },
];

export const PLACEHOLDER_PACKAGES: TravelPackage[] = [
  { id: "1", slug: "cappadocia-oct-2027", order: 1, featured: true, status: "active", type: "photography_only", destination: "Cappadocia, Turkey", title: "1. Cappadocia (October 2027)", description: "This region in East Central Anatolia in Turkey is among Mother Earth's most surreal and unbelievable landscapes. It is also the home of the ruggedly beautiful Yilki and Anatolian horses who roam over a vast stretch of land or reside in ranches nestled into the region's volcanic rock.", noteForPhotographers: "Please note that this trip is specifically for photographers.", heroImage: { id: "img-1", url: "https://placehold.co/1184x789/1a1a1a/555?text=Cappadocia", altText: "Horses in Cappadocia, Turkey" }, gallery: [], groupSizeMax: 12, spotsRemaining: 8, startDate: "2027-10-01", createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
  { id: "2", slug: "botswana-tbd", order: 2, featured: false, status: "active", type: "group", destination: "Botswana", title: "2. Botswana", description: "The Okavango Delta is home to animals of all kinds, many of which are endangered. It is one of only a few places on Earth where you can find storied animals, such as white and black rhinoceros, cheetahs, lions, elephants, and more, all in one location.", heroImage: { id: "img-2", url: "https://placehold.co/576x384/1a1a1a/555?text=Botswana", altText: "Wildlife in the Okavango Delta" }, gallery: [], groupSizeMax: 10, spotsRemaining: 10, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
  { id: "3", slug: "kenya-nov-2027", order: 3, featured: false, status: "active", type: "group", destination: "Kenya", title: "3. Kenya (November 2027)", tagline: "Only 5 Spaces Left", taglineColor: "red", description: "Kenya is home to some of the most incredible wildlife on Earth, making it the perfect destination for anyone who wants to immerse themselves in East Africa's spectacular wild landscape while in a small group setting.", heroImage: { id: "img-3", url: "https://placehold.co/576x385/1a1a1a/555?text=Kenya", altText: "Wildlife in Kenya" }, gallery: [], groupSizeMax: 10, spotsRemaining: 5, startDate: "2027-11-01", createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
  { id: "4", slug: "rwanda-tbd", order: 4, featured: false, status: "active", type: "group", destination: "Rwanda", title: "4. Rwanda", description: "In Rwanda, we will embark on once-in-a-lifetime treks into the Virungas to see the mountain gorillas in their surreal, natural habitat. This is available as a pre-trip extension before traveling to Kenya.", heroImage: { id: "img-4", url: "https://placehold.co/576x385/1a1a1a/555?text=Rwanda", altText: "Mountain gorillas in Rwanda" }, gallery: [], groupSizeMax: 8, spotsRemaining: 8, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
  { id: "5", slug: "alaska-aug-2026", order: 5, featured: false, status: "active", type: "group", destination: "Alaska", title: "5. Alaska (Late August 2026)", tagline: "Only 5 Spaces Left", taglineColor: "red", description: "During the annual salmon run, a record number of brown bears descend on Katmai National Park on the Alaskan peninsula. You'll access this remote swath of land via float plane to photograph intimate encounters with brown bears of all shapes and sizes.", heroImage: { id: "img-5", url: "https://placehold.co/576x384/1a1a1a/555?text=Alaska", altText: "Brown bears in Katmai, Alaska" }, gallery: [], groupSizeMax: 8, spotsRemaining: 5, startDate: "2026-08-20", createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
  { id: "6", slug: "tanzania-tbd", order: 6, featured: false, status: "active", type: "group", destination: "Tanzania", title: "6. Tanzania", description: "During this itinerary, you'll explore the wild expanses of Tanzania, encountering some of the most memorable African wildlife during one of the most exciting, fascinating, and lively times of the year.", heroImage: { id: "img-6", url: "https://placehold.co/576x385/1a1a1a/555?text=Tanzania", altText: "Serengeti, Tanzania" }, gallery: [], groupSizeMax: 10, spotsRemaining: 10, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
  { id: "7", slug: "svalbard-may-2027", order: 7, featured: false, status: "active", type: "group", destination: "Svalbard, Norway", title: "7. Svalbard (May 2027)", description: "The Norwegian Arctic landscape offers one of the most stunning natural experiences in the world. From polar bears to glaciers to whales, you will immerse yourself in the beauty of this surreal territory aboard a small, intimate expedition boat under the midnight sun.", heroImage: { id: "img-7", url: "https://placehold.co/576x385/1a1a1a/555?text=Svalbard", altText: "Arctic landscape, Svalbard" }, gallery: [], groupSizeMax: 12, spotsRemaining: 12, startDate: "2027-05-01", createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
];

export const PLACEHOLDER_TESTIMONIALS: TravelTestimonial[] = [
  { id: "t1", clientName: "Howard S.", destination: "Kenya 2023", theme: "dark", side: "left", featured: true, imageUrl: "https://placehold.co/1440x900/111/333?text=Kenya", quote: '"I\'ve been to Africa 7 times; three of those trips were in the last 12 months. Drew\'s was the best by far; absolutely nothing could be improved. Everything was perfect, from Drew\'s pre-trip info through our various flights home! Our accommodations, food, and the array of animals we saw exceeded my expectations in every way. I look forward to our next expedition together."' },
  { id: "t2", clientName: "Annie F.", destination: "Svalbard 2023", theme: "dark", side: "right", featured: true, imageUrl: "https://placehold.co/1440x900/111/333?text=Svalbard", quote: '"I\'ve always wanted to see the Arctic landscape. Joining Drew on this trip, even if I wasn\'t attending for photography, was a privilege I hope I can repeat. An opportunity to travel with Drew, as a photographer or not, is a fantastic experience."' },
  { id: "t3", clientName: "Rachel S.", destination: "Svalbard + Alaska 2023", theme: "light", side: "left", featured: true, imageUrl: "https://placehold.co/1440x775/ddd/999?text=Arctic", quote: '"I\'ve traveled on multiple trips with Drew, resulting in outstanding photos. Photographing wildlife is all about access and proximity. As our photography guide, Drew was excellent  always open about all aspects of photography and willing to discuss composition. These were the trips of a lifetime."' },
  { id: "t4", clientName: "Erin & Bob C.", destination: "Kenya 2023", theme: "dark", side: "right", featured: true, imageUrl: "https://placehold.co/1440x900/111/333?text=Savanna", quote: '"Drew Doggett is a brilliant artist and the perfect person to lead small groups through a safari adventure. If photography is your focus, it is an opportunity to learn from the best in the business. We will be back!"' },
];
